In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.tree import DecisionTreeClassifier

C:\Users\Swaraj Badhei\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\Swaraj Badhei\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
df=pd.read_csv('balance-scale.csv').values

In [4]:
y=df[:,0]
x=df[:,1:]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [7]:
gini=DecisionTreeClassifier(criterion='gini',max_depth=4,min_samples_leaf=5)

In [8]:
gini.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [9]:
pred=gini.predict(X_test)

In [16]:
print('using gini index')
print('accuracy:',accuracy_score(pred,y_test))
print('confusion matrix:',confusion_matrix(pred,y_test))
print('classification resport',classification_report(pred,y_test))

using gini index
accuracy: 0.8155339805825242
confusion matrix: [[ 0  0  0]
 [ 6 83 12]
 [ 8 12 85]]
classification resport               precision    recall  f1-score   support

           B       0.00      0.00      0.00         0
           L       0.87      0.82      0.85       101
           R       0.88      0.81      0.84       105

    accuracy                           0.82       206
   macro avg       0.58      0.54      0.56       206
weighted avg       0.88      0.82      0.84       206



In [17]:
entropy=DecisionTreeClassifier(criterion='entropy',max_depth=4,min_samples_leaf=5)

In [18]:
entropy.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [19]:
pred2=entropy.predict(X_test)

In [20]:
print('using entropy')
print('accuracy:',accuracy_score(pred2,y_test))
print('confusion matrix:',confusion_matrix(pred2,y_test))
print('classification resport',classification_report(pred2,y_test))

using entropy
accuracy: 0.7281553398058253
confusion matrix: [[ 0  0  0]
 [ 9 79 26]
 [ 5 16 71]]
classification resport               precision    recall  f1-score   support

           B       0.00      0.00      0.00         0
           L       0.83      0.69      0.76       114
           R       0.73      0.77      0.75        92

    accuracy                           0.73       206
   macro avg       0.52      0.49      0.50       206
weighted avg       0.79      0.73      0.75       206



C:\Users\Swaraj Badhei\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
