In [4]:
from sklearn_pandas import CategoricalImputer
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [5]:
df=pd.DataFrame('a b c a a b a c c a a a b a b'.split(),dtype='category')

In [6]:
print(df)

    0
0   a
1   b
2   c
3   a
4   a
5   b
6   a
7   c
8   c
9   a
10  a
11  a
12  b
13  a
14  b


In [7]:
ci=CategoricalImputer(missing_values='c')

In [8]:
ci.fit_transform(df[0])

array(['a', 'b', 'a', 'a', 'a', 'b', 'a', 'a', 'a', 'a', 'a', 'a', 'b',
       'a', 'b'], dtype=object)

In [9]:
le=LabelEncoder()

In [10]:
le.fit_transform(df)

C:\Users\Swaraj Badhei\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 1, 2, 0, 0, 1, 0, 2, 2, 0, 0, 0, 1, 0, 1])

In [11]:
one_hot_df=pd.get_dummies(df,prefix='abc')

In [12]:
one_hot_df.shape

(15, 3)

In [13]:
dec=pd.get_dummies(df,prefix='abc',drop_first=True)

In [14]:
dec

abc_b  abc_c
0       0      0
1       1      0
2       0      1
3       0      0
4       0      0
5       1      0
6       0      0
7       0      1
8       0      1
9       0      0
10      0      0
11      0      0
12      1      0
13      0      0
14      1      0

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
ohe=OneHotEncoder(categories='auto')

In [17]:
val=ohe.fit_transform(le.fit_transform(df).reshape(-1,1)).todense()

In [18]:
print(val)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [19]:
#maam did this one
y=le.fit_transform(df)

C:\Users\Swaraj Badhei\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [20]:
df[0]=y

In [21]:
ohe.fit_transform(df).toarray()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [22]:
pd.get_dummies?