In [1]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [7]:
df=pd.read_csv('wine/wine.csv').values

In [10]:
x=df[:,1:]
y=df[:,0]

In [11]:
y.shape

(177,)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [13]:
obj=SVC(kernel='linear')

In [14]:
obj.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [15]:
pred=obj.predict(X_test)

In [16]:
print('linear kernel')
print('accuracy score:',accuracy_score(pred,y_test))
print('confusion matrix:',confusion_matrix(pred,y_test))
print('Classification report',classification_report(pred,y_test))

linear kernel
accuracy score: 0.9491525423728814
confusion matrix: [[19  0  0]
 [ 1 23  0]
 [ 0  2 14]]
Classification report               precision    recall  f1-score   support

         1.0       0.95      1.00      0.97        19
         2.0       0.92      0.96      0.94        24
         3.0       1.00      0.88      0.93        16

    accuracy                           0.95        59
   macro avg       0.96      0.94      0.95        59
weighted avg       0.95      0.95      0.95        59



In [17]:
obj2=SVC(kernel='rbf',gamma=0.5)

In [18]:
obj2.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.5, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [19]:
pred2=obj2.predict(X_test)

In [20]:
print('Radial basis function')
print('accuracy score:',accuracy_score(pred2,y_test))
print('confusion matrix:',confusion_matrix(pred2,y_test))
print('Classification report',classification_report(pred2,y_test))

Radial basis function
accuracy score: 0.423728813559322
confusion matrix: [[ 0  0  0]
 [20 25 14]
 [ 0  0  0]]
Classification report               precision    recall  f1-score   support

         1.0       0.00      0.00      0.00         0
         2.0       1.00      0.42      0.60        59
         3.0       0.00      0.00      0.00         0

    accuracy                           0.42        59
   macro avg       0.33      0.14      0.20        59
weighted avg       1.00      0.42      0.60        59



C:\Users\Swaraj Badhei\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [21]:
obj3=SVC(kernel='poly',degree=5)

In [22]:
obj3.fit(X_train,y_train)

C:\Users\Swaraj Badhei\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=5, gamma='auto_deprecated',
    kernel='poly', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [23]:
pred3=obj3.predict(X_test)

In [24]:
print('Polynomial Kernel')
print('accuracy score:',accuracy_score(pred3,y_test))
print('confusion matrix:',confusion_matrix(pred3,y_test))
print('Classification report',classification_report(pred3,y_test))

Polynomial Kernel
accuracy score: 0.847457627118644
confusion matrix: [[15  0  1]
 [ 4 22  0]
 [ 1  3 13]]
Classification report               precision    recall  f1-score   support

         1.0       0.75      0.94      0.83        16
         2.0       0.88      0.85      0.86        26
         3.0       0.93      0.76      0.84        17

    accuracy                           0.85        59
   macro avg       0.85      0.85      0.84        59
weighted avg       0.86      0.85      0.85        59



In [32]:
#calcualting precision and recall
#precision=tp/(tp+fp)
#recall=tp/(tp+fn)

In [26]:
import numpy as np

In [27]:
arr=np.array([[5,6],[7,8]])

In [31]:
np.sum(arr,axis=1)

array([11, 15])

In [33]:
print('recall:',arr[0,0]/np.sum(arr,axis=0)[0])

precision: 0.4166666666666667


In [34]:
print('precision:',arr[0,0]/(arr[0,0]+arr[1,1]))

precision: 0.38461538461538464


In [35]:
arr2=np.array([[13,0,0],[0,16,4],[0,0,12]])

In [36]:
arr2

array([[13,  0,  0],
       [ 0, 16,  4],
       [ 0,  0, 12]])

In [39]:
print('precision for class 0:',arr2[0,0]/np.sum(arr2,axis=1)[0])
print('precision for class 1:',arr2[1,1]/np.sum(arr2,axis=1)[1])
print('precision for class 2:',arr2[2,2]/np.sum(arr2,axis=1)[2])

precision for class 0: 1.0
precision for class 1: 0.8
precision for class 2: 1.0


In [40]:
print('recall for class 0:',arr2[0,0]/np.sum(arr2,axis=0)[0])
print('recall for class 1:',arr2[1,1]/np.sum(arr2,axis=0)[1])
print('recall for class 2:',arr2[2,2]/np.sum(arr2,axis=0)[2])

recall for class 0: 1.0
recall for class 1: 1.0
recall for class 2: 0.75


In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.14.0'